<?php
/**
 * Zend Framework 2 - PHP-Magazin Service-Manager
 *
 * Beispiele für ZF2 Service-Manager
 *
 * @package    Shop
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */
use Zend\Debug\Debug;

?>
<div class="jumbotron">
    <h1>Ausgabe Entitäten aus Service-Manager</h1>
</div>
<p>
    <?php Debug::dump($this->bellPrincess) ?>
    <?php Debug::dump($this->wheel10Inch) ?>
    <?php Debug::dump($this->wheel12Inch) ?>
    <?php Debug::dump($this->bikeSmall) ?>
    <?php Debug::dump($this->bikeMedium) ?>
</p>
