<?php
/**
 * Zend Framework 2 - PHP-Magazin Service-Manager
 *
 * Beispiele für ZF2 Service-Manager
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Herzlich Willkommen!');

?>
<div class="jumbotron">
    <h1>Zend Framework 2 - PHP-Magazin Service-Manager</h1>
    <p>
        In diesem Projekt finden Sie die lauffähigen Beispiele für den Artikel
        zum Zend Framework 2 Service-Manager aus dem PHP Magazin.
    </p>
</div>

